### ISSUE TITLE
Cronjob that parses changelog to automatically update the features page

### ISSUE THREAD

**Issue by JarnoVgr** [Limetric/OpenRCT2.org#2]

**Comment by runelaenen** [comment]
Can't this easily be achieved using a cache file?
Pseudo php code:
```
if(file_exists($cache) && filemtime($cache) > time()-60*60*24){
// return cache file contents
} else {
// download features thing from github, 
// save it as $cache
// return the contents
}
```

This way the server will only poll Github at most once a day. 
Every first visit after the 24 hours have passed will load a bit slower, but I think that's the only downside to this approach.

**Comment by JarnoVgr** [comment]
Fixed
