### ISSUE TITLE
HTTPS weak ciphers

### ISSUE THREAD

**Issue by JarnoVgr** [Limetric/OpenRCT2.org#27]
As stated in [this](https://github.com/JarnoVgr/OpenRCT2.org/issues/25#issuecomment-391528922) comment, the ciphers of openrct2.org are weak. 

While I would like to update the cipher list. I'm unsure whether it affects backwards compatibility with older browsers/setups. I.e. Android 4.x.

**Comment by TheAssassin** [comment]
@JarnoVgr the ciphers aren't all weak, only some of them are theoretically vulnerable. There's no critical bugs. There is a reason the SSL check page rates your page A. The page is secure as it is. If you change the ciphers, users with older versions of the browsers won't most likely be able to connect any more, which is probably not intended. I'd leave things as they are at the moment.

**Comment by qwertychouskie** [comment]
According to the test on my site with those ciphers (https://www.ssllabs.com/ssltest/analyze.html?d=jacobspctuneup.tk), the only systems to not connect are IE on XP and Android 2.3 (and some ancient java versions).  Firefox and Chrome on XP are fine though, and anyone using XP should be using FF, as IE 6-8 breaks most pages/sites anyways.  Also, according to Google (https://developer.android.com/about/dashboards/) Android 2.3 has less than 0.3% market share.

**Comment by JarnoVgr** [comment]
Hosting will move to Google Cloud and thus the ciphers recommend by Google will be used.
