### ISSUE TITLE
Gitter is linked on openrct.org yet Gitter is not used

### ISSUE THREAD

**Issue by Willbycraft** [Limetric/OpenRCT2.org#51]
# This is what the conversation is
Perhaps the button should link to Discord instead, and uses a [Discord logo](https://discord.com/new/branding) for the button.

![conversation](https://cdn.discordapp.com/attachments/691736850980667514/744118586909392976/unknown.png)

**Comment by JarnoVgr** [comment]
This will be fixed a.s.a.p. as I'm waiting for a dependency to be updated in the upcoming days to properly upgrade this project. 

Thanks for letting me know. 👍

**Comment by JarnoVgr** [comment]
Resolved in https://github.com/Limetric/OpenRCT2.org/commit/31ef2a2e28437b409abbbc58fbd36236b8edbc0e.
